language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=4.0.*

before_install:
  - export SYMFONY_DEPRECATIONS_HELPER=strict
  - composer self-update

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction
script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs . --standard=vendor/m6web/symfony2-coding-standard/Symfony2 -sp --ignore=vendor,Tests --extensions=php

notifications:
  email:
    - travis-ci@kitpages.fr
